INSERT INTO USER (USERNAME, PASSWORD, ENABLED) VALUES ('admin', 'password', TRUE);

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES ('admin', 'ROLE_ADMIN');

INSERT INTO BLOG_POST (TITLE, CONTENT, DRAFT, PUBLISHDATE, USER_ID) VALUES ('FIRST POST', 'TEST CONTENT', false, NOW(), 1);

